name: Keep Fresh
on: [push, pull_request]

jobs:
  auto-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v1.1.1
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{ secrets.github_token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: |
          git config --global user.email "ashersaupingomez@gmail.com"
          git config --global user.name "Asher Gomez"
      - run: npm version patch
      - run: npm install --ignore-scripts
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
